### ISSUE TITLE
로그인 서버 개발

### ISSUE THREAD

**Issue by changhwa** [changhwa/voyage#5]
- [ ] 페이스북 로그인
- [x] 깃허브 로그인
- [x] 로그아웃

**Comment by changhwa** [comment]
페이스북 로그인은 @urosaria  구현예정

**Comment by dongyeonlee** [comment]
트위터는 구현 안하시나요? @changhwa

**Comment by changhwa** [comment]
@dongyeonlee  트위터도 구현할예정입니다. 
현재 우선순위가 글작성에 몰려있어 해당 기능들부터 구현중입니다.
참고부탁드립니다.
